# Generated by Django 4.2.16 on 2024-11-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='音乐名')),
                ('poster', models.ImageField(upload_to='music_posters/', verbose_name='音乐海报')),
                ('music_file', models.FileField(upload_to='music_mp4_files/', verbose_name='音乐文件（MP4）')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='歌词')),
            ],
        ),
    ]
