# Generated by Django 4.2.16 on 2024-11-20 08:56

from django.db import migrations, models
import musicapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='music_file',
        ),
        migrations.AddField(
            model_name='music',
            name='media_file',
            field=models.FileField(default='',null=True, upload_to='media_files/', validators=[musicapp.models.validate_audio_video_file], verbose_name='媒体文件'),
        ),
        migrations.AddField(
            model_name='music',
            name='media_type',
            field=models.CharField(choices=[('audio', '音频'), ('video', '视频')], default='未知', max_length=5, verbose_name='媒体类型'),
        ),
        migrations.AlterField(
            model_name='music',
            name='poster',
            field=models.ImageField(upload_to='media_posters/', verbose_name='媒体封面'),
        ),
    ]
