# Generated by Django 4.2.16 on 2024-11-20 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0004_alter_music_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('watchAgain', models.BooleanField()),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
